# .air.toml — dev only

root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
# 构建目标指向 ./cmd/api，避免 "no Go files in /app"
cmd = "go build -trimpath -buildvcs=false -tags=dev -o ./tmp/main ./cmd/api"
bin = "./tmp/main"
full_bin = "GIN_MODE=debug ./tmp/main"

# 保证 tmp 目录存在，避免首次构建时路径不存在
pre_cmd = ["sh -c 'mkdir -p ./tmp'"]

# 构建与重启策略
delay = 250
stop_on_error = true
send_interrupt = true
kill_delay = "500ms"

# 监听范围 & 排除
include_ext = ["go","tpl","tmpl","html","yaml","yml","json","toml","sql"]
exclude_dir = ["tmp","vendor","testdata","assets","frontend",".git","node_modules"]
exclude_regex = ["_test\\.go$","\\.swp$","~$","^\\.idea/","^\\.vscode/"]

# 其他保持默认
args_bin = []
exclude_file = []
exclude_unchanged = false
follow_symlink = false
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
rerun = false
rerun_delay = 500

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
silent = false
time = true

[misc]
clean_on_exit = true

[proxy]
enabled = false
app_port = 0
proxy_port = 0

[screen]
clear_on_rebuild = true
keep_scroll = true