version: "3.9"

services:
  # API 开发服务 (Go + Air)
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ssp-api-dev
    ports:
      - "8080:8080"
    volumes:
      # 将本地代码实时同步到容器中
      - .:/app
    environment:
      # 从 .env 文件读取配置，并传递给 Go 应用
      - SSP_SERVER_MODE=debug
      - SSP_SERVER_PORT=8080
      - SSP_DATABASE_DSN=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable
      - GIN_MODE=debug
    depends_on:
      - db
    networks:
      - ssp-dev-net

  # 数据库服务
  db:
    image: postgres:16-alpine
    container_name: ssp-db-dev
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      # 映射到 127.0.0.1，方便本地 GUI 工具连接，且更安全
      - "127.0.0.1:5432:5432"
    volumes:
      # 持久化数据库数据
      - ssp_dev_pgdata:/var/lib/postgresql/data
    networks:
      - ssp-dev-net

networks:
  ssp-dev-net:

volumes:
  ssp_dev_pgdata: