version: "3.9"

name: ssp-staging

services:
  db:
    image: postgres:16-alpine
    container_name: ssp-db
    environment:
      POSTGRES_DB: ssp
      POSTGRES_USER: ssp
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?set in .env.staging}
    volumes:
      - ssp_pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks: [ssp]

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ssp-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      SSP_SERVER_MODE: release
      SSP_SERVER_PORT: "8080"
      SSP_DATABASE_DRIVER: postgres
      SSP_DATABASE_DSN: postgres://ssp:${POSTGRES_PASSWORD}@db:5432/ssp?sslmode=disable
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/api/v1/healthz >/dev/null || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks: [ssp]

networks:
  ssp: {}

volumes:
  ssp_pgdata: {}