/*
 * 学生服务平台 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UserUpdate struct {

	Email string `json:"email"`

	Name string `json:"name,omitempty"`

	Phone string `json:"phone,omitempty"`

	Dept string `json:"dept,omitempty"`

	AllowEmail bool `json:"allow_email,omitempty"`
}
