/*
 * 学生服务平台 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type TicketMessage struct {

	Id int32 `json:"id,omitempty"`

	TicketId int32 `json:"ticket_id,omitempty"`

	SenderUserId int32 `json:"sender_user_id,omitempty"`

	Body string `json:"body,omitempty"`

	IsInternalNote bool `json:"is_internal_note,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`
}
