/*
 * 学生服务平台 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type AuditLog struct {

	Id int32 `json:"id,omitempty"`

	ActorUserId int32 `json:"actor_user_id,omitempty"`

	Action string `json:"action,omitempty"`

	Entity string `json:"entity,omitempty"`

	EntityId int32 `json:"entity_id,omitempty"`

	// 变更快照（JSON）
	Diff map[string]interface{} `json:"diff,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`
}
