/*
 * 学生服务平台 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AdminStatsGet200Response struct {

	Totals AdminStatsGet200ResponseTotals `json:"totals,omitempty"`

	ByCategory []AdminStatsGet200ResponseByCategoryInner `json:"by_category,omitempty"`

	DailyTrend []AdminStatsGet200ResponseDailyTrendInner `json:"daily_trend,omitempty"`

	AdminWorkload []AdminStatsGet200ResponseAdminWorkloadInner `json:"admin_workload,omitempty"`
}
