/*
 * 学生服务平台 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type TicketStatus string

// List of TicketStatus
const (
	NEW TicketStatus = "NEW"
	CLAIMED TicketStatus = "CLAIMED"
	IN_PROGRESS TicketStatus = "IN_PROGRESS"
	RESOLVED TicketStatus = "RESOLVED"
	CLOSED TicketStatus = "CLOSED"
	SPAM_PENDING TicketStatus = "SPAM_PENDING"
	SPAM_CONFIRMED TicketStatus = "SPAM_CONFIRMED"
	SPAM_REJECTED TicketStatus = "SPAM_REJECTED"
)
