/*
 * 学生服务平台 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ImagesPost201Response struct {

	ImageId int32 `json:"image_id,omitempty"`

	Sha256 string `json:"sha256,omitempty"`

	Mime string `json:"mime,omitempty"`

	Width int32 `json:"width,omitempty"`

	Height int32 `json:"height,omitempty"`
}
