/*
 * 学生服务平台 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type TicketsIdMessagesPostRequest struct {

	Body string `json:"body"`

	// 管理员内部备注（学生不可见）
	IsInternalNote bool `json:"is_internal_note,omitempty"`
}
