/*
 * 学生服务平台 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type SpamFlag struct {

	TicketId int32 `json:"ticket_id,omitempty"`

	FlaggedByAdminId int32 `json:"flagged_by_admin_id,omitempty"`

	Reason string `json:"reason,omitempty"`

	Status string `json:"status,omitempty"`

	ReviewedBySuperAdminId *int32 `json:"reviewed_by_super_admin_id,omitempty"`

	ReviewedAt *time.Time `json:"reviewed_at,omitempty"`
}
