/*
 * 学生服务平台 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type TicketsIdRatePostRequest struct {

	Stars int32 `json:"stars"`

	Comment string `json:"comment,omitempty"`
}
