/*
 * 学生服务平台 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type Ticket struct {

	Id int32 `json:"id,omitempty"`

	UserId int32 `json:"user_id,omitempty"`

	Title string `json:"title,omitempty"`

	Content string `json:"content,omitempty"`

	Category string `json:"category,omitempty"`

	IsUrgent bool `json:"is_urgent,omitempty"`

	IsAnonymous bool `json:"is_anonymous,omitempty"`

	Status TicketStatus `json:"status,omitempty"`

	AssignedAdminId *int32 `json:"assigned_admin_id"`

	ClaimedAt *time.Time `json:"claimed_at,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`

	ImageIds []int32 `json:"image_ids,omitempty"`
}
