/*
 * 学生服务平台 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AdminStatsGet200ResponseTotals struct {

	Tickets int32 `json:"tickets,omitempty"`

	Resolved int32 `json:"resolved,omitempty"`

	Closed int32 `json:"closed,omitempty"`

	SpamConfirmed int32 `json:"spam_confirmed,omitempty"`
}
