/*
 * 学生服务平台 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type CannedReply struct {

	Id int32 `json:"id,omitempty"`

	AdminUserId int32 `json:"admin_user_id,omitempty"`

	Title string `json:"title,omitempty"`

	Body string `json:"body,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`
}
