/*
 * 学生服务平台 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AdminStatsGet200ResponseDailyTrendInner struct {

	Date string `json:"date,omitempty"`

	Count int32 `json:"count,omitempty"`
}
