/*
 * 学生服务平台 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type User struct {

	Id int32 `json:"id,omitempty"`

	Email string `json:"email,omitempty"`

	Name string `json:"name,omitempty"`

	Role Role `json:"role,omitempty"`

	Phone *string `json:"phone,omitempty"`

	Dept *string `json:"dept,omitempty"`

	IsActive bool `json:"is_active,omitempty"`

	// 允许邮件提醒
	AllowEmail bool `json:"allow_email,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
