/*
 * 学生服务平台 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Image struct {

	Id int32 `json:"id,omitempty"`

	Sha256 string `json:"sha256,omitempty"`

	Mime string `json:"mime,omitempty"`

	Size int32 `json:"size,omitempty"`

	Width int32 `json:"width,omitempty"`

	Height int32 `json:"height,omitempty"`

	ObjectKey string `json:"object_key,omitempty"`

	RefCount int32 `json:"ref_count,omitempty"`
}
