/*
 * 学生服务平台 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AuthLoginPost200Response struct {

	// JWT
	AccessToken string `json:"access_token,omitempty"`

	TokenType string `json:"token_type,omitempty"`

	ExpiresIn int32 `json:"expires_in,omitempty"`
}
