/*
 * 学生服务平台 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Role : 角色
type Role string

// List of Role
const (
	STUDENT Role = "STUDENT"
	ADMIN Role = "ADMIN"
	SUPER_ADMIN Role = "SUPER_ADMIN"
)
