/*
 * 学生服务平台 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AdminStatsGet200ResponseAdminWorkloadInner struct {

	AdminId int32 `json:"admin_id,omitempty"`

	Name string `json:"name,omitempty"`

	TicketsHandled int32 `json:"tickets_handled,omitempty"`
}
