/*
 * 学生服务平台 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type Rating struct {

	Id int32 `json:"id,omitempty"`

	TicketId int32 `json:"ticket_id,omitempty"`

	UserId int32 `json:"user_id,omitempty"`

	Stars int32 `json:"stars,omitempty"`

	Comment string `json:"comment,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`
}
