/*
 * 学生服务平台 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type TicketCreate struct {

	Title string `json:"title"`

	Content string `json:"content"`

	Category string `json:"category"`

	IsUrgent bool `json:"is_urgent"`

	IsAnonymous bool `json:"is_anonymous"`

	// 由 /images 上传返回的 image_id 列表
	ImageIds []int32 `json:"image_ids,omitempty"`
}
