# 邮件服务配置示例
email:
  smtp_host: "smtp.gmail.com"       # SMTP服务器地址
  smtp_port: 587                    # SMTP端口 (Gmail: 587, QQ: 587, 163: 25)
  smtp_username: "your-email@gmail.com"  # SMTP用户名
  smtp_password: "your-app-password"     # SMTP密码或应用专用密码
  from_email: "noreply@your-domain.com"  # 发件人邮箱
  from_name: "学生服务平台"               # 发件人姓名
  tls_enabled: true                      # 是否启用TLS加密

# Redis配置（用于异步任务队列）
redis:
  addr: "localhost:6379"    # Redis地址
  password: ""              # Redis密码（如果有）
  db: 0                     # Redis数据库编号

# 异步任务配置
worker:
  concurrency: 10           # 并发worker数量
  queues:
    critical: 6             # 紧急队列权重
    default: 3              # 默认队列权重
    low: 1                  # 低优先级队列权重
  retry_delay: "1s"         # 重试延迟
  max_retry: 3              # 最大重试次数

# 前端配置
frontend:
  base_url: "https://your-frontend-domain.com"  # 前端基础URL，用于生成邮件中的链接